=== leedarKen/cflow/src/main/resources/process/process.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="process">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="processForm" type="processFormType" minOccurs="0"/>
                <xs:element name="taskList" type="taskListType" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="version" type="xs:string"/>
            <xs:attribute name="startUserRole" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="processFormType">
        <xs:sequence>
            <xs:element name="column" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="type" type="columnType"/>
                    <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="taskListType">
        <xs:sequence>
            <xs:element name="task" type="taskType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="taskType">
        <xs:sequence>
            <xs:element name="executor" type="executorType" maxOccurs="1" minOccurs="1"/>
            <xs:element name="input" type="inputType" maxOccurs="1" minOccurs="0"/>
            <xs:element name="submit" type="inputType" minOccurs="1"/>
            <xs:element name="ruleList" type="ruleListType" maxOccurs="1" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="taskTypeAttribute" />
        <xs:attribute name="action" type="actionTypeList"/>
    </xs:complexType>

    <xs:complexType name="executorType">
        <xs:sequence>
            <xs:element name="user_id" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="strategy" type="taskRoleStrategyType" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="inputType">
        <xs:sequence>
            <xs:element name="column" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="isRequire" type="xs:boolean"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

    </xs:complexType>
    <xs:complexType name="ruleListType">
        <xs:sequence>
            <xs:element name="rule" type="ruleType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ruleType">
        <xs:sequence>
            <xs:element name="condition" type="conditionType" maxOccurs="unbounded" minOccurs="1"/>
            <xs:element name="trigger" type="triggerType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="conditionType">
        <xs:sequence>
            <xs:element name="column" minOccurs="1" maxOccurs="unbounded" type="conditionColumnType" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="conditionColumnType">

        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="valueCondition" type="valueConditionType"/>
    </xs:complexType>
    <xs:complexType name="triggerType">
         <xs:attribute name="ref" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="triggerTaskType">
        <xs:attribute name="ref" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="actionTypeList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Input"/>
            <xs:enumeration value="Approve"/>
            <xs:enumeration value="Notice"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="taskRoleStrategyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Role"/>
            <xs:enumeration value="Leader"/>
            <xs:enumeration value="Constant"/>
            <xs:enumeration value="Assign"/>
            <xs:enumeration value="Others"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="columnType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Date"/>
            <xs:enumeration value="Number"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="List"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="taskTypeAttribute">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Begin"/>
            <xs:enumeration value="End"/>
            <xs:enumeration value="Process"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="valueConditionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Equal"/>
            <xs:enumeration value="Smaller"/>
            <xs:enumeration value="Greater"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== leedarKen/cflow/src/main/resources/process/bdm_travel_process_1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<process id="bdm_travel" name="BDM Travel Process" version="1.0.0" startUserRole="BDM"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="process.xsd">
    <processForm>
        <column id="TravelAmount" type="Number" name="Travel Amount"/>
        <!-- <column id="DepartureDate" type="Date" name="Departure Date"/>
        <column id="ReturnDate" type="Date" name="Return Date"/>
        <column id="Destination" type="String" name="Destination"/>
        <column id="Reason" type="String" name="Reason"/>-->
        <column id="outOfChina" type="String" name="Out Of China"/>
    </processForm>

    <taskList>
        <task id="apply_travel" name="Apply Travel" action="Input" type="Begin">
            <executor strategy="Role" value="BDM" />
            <input>
                <column id="TravelAmount" isRequire="true"/>
                <column id="DepartureDate" isRequire="true"/>
                <column id="ReturnDate" isRequire="true"/>
                <column id="Destination" isRequire="true"/>
                <column id="Reason" isRequire="true"/>
                <column id="outOfChina" isRequire="true"/>
            </input>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="success" type="equal"/>
                    </condition>
                    <trigger ref="bdm_leader_approve"/>
                </rule>
            </ruleList>
        </task>
        <task id="bdm_leader_approve" name="BDM Leader Approve" action="Approve" type="Process">
            <executor strategy="Leader" value=""/>
            <submit>
                <column id="action"/>
                <column id="TravelAmount"/>
                <column id="outOfChina"/>
            </submit>
            <ruleList>
                <rule id="in_china_to_fiance">
                    <condition>
                        <column id="action" value="approve" type="equal"/>
                        <column id="TravelAmount" value="4000" type="smaller"/>
                        <column id="outOfChina" value="False" type="equal"/>
                    </condition>
                    <trigger ref="fiance_approve"/>
                </rule>
               <rule id="out_china_to_manager">
                   <condition>
                       <column id="action" value="approve" type="Equal"/>
                       <column id="TravelAmount" value="4000" type="Smaller"/>
                       <column id="outOfChina" value="True" type="Equal"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="greater_than_4000">
                   <condition>
                       <column id="action" value="approve" type="Equal"/>
                       <column id="TravelAmount" value="4000" type="Greater"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="reject">
                <condition>
                    <column id="action" value="reject" type="equal"/>
                </condition>
                <trigger  ref="apply_travel"/>
            </rule>
            </ruleList>
        </task>
        <task id="manager_approve" name="Manager Approve" action="Approve" type="Process">
            <executor strategy="Constant" value="">
                <user_id id="255" />
                <user_id id="3383" />
            </executor>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="approve" type="equal"/>
                    </condition>
                    <trigger ref="admin_order"/>
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="reject" type="equal"/>
                    </condition>
                    <trigger ref="apply_travel"/>
                </rule>
            </ruleList>
        </task>
        <task id="fiance_approve" name="Fiance Approve" action="Approve" type="Process">
            <executor strategy="Constant" value="">
                <user_id id="250" />
                <user_id id="3383" />
            </executor>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="approve" type="equal"/>
                    </condition>
                    <trigger ref="admin_order"/>
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="reject" type="equal"/>
                    </condition>
                    <trigger ref="apply_travel"/>
                </rule>
            </ruleList>
        </task>

        <task id="admin_order" name="Admin Order" action="Notice" type="End">
            <executor strategy="Role" value="ADMIN" />
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="finish" type="equal"/>
                    </condition>
                    <trigger ref="end" />
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="cancel" type="equal"/>
                    </condition>
                    <trigger  ref="apply_travel" />
                </rule>
            </ruleList>
        </task>
    </taskList>
</process>

=== leedarKen/cflow/src/main/resources/process/bdm_travel_payment_process_1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<process id="bdm_travel" name="BDM Travel Process" version="1.0.0" startUserRole="BDM"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="process.xsd">
    <processForm>
        <column id="TravelAmount" type="Currency" name="Travel Amount"/>
    </processForm>
    <taskList>
        <task id="apply_travel_payment" name="Apply Travel Payment" action="Input" type="Begin">
            <executor strategy="Role" value="BDM" />
            <input>
                <column id="TravelAmount"/>
            </input>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="success" valueType="Equal"/>
                    </condition>
                    <trigger ref="fiance_approve"/>
                </rule>
            </ruleList>
        </task>
        <task id="fiance_approve" name="Fiance Approve" action="Approve" type="Process">
            <executor strategy="Role" value="Fiance Member" />
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="approve" valueType="Equal"/>
                    </condition>
                    <trigger ref="end"/>
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="reject" valueType="Equal"/>
                    </condition>
                    <trigger ref="apply_travel_payment"/>
                </rule>
            </ruleList>
        </task>

    </taskList>
</process>

=== leedarKen/cflow/src/main/resources/process/bdm_travel_pre-application_process_1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<process id="bdm_travel_pre-application_process" name="BDM Travel Process" version="1.0.0" startUserRole="BDM"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="process.xsd">
    <processForm>
        <column id="TravelAmount" type="Currency" name="Travel Amount"/>
        <column id="outOfChina" type="String" name="Out Of China"/>
    </processForm>

    <taskList>
        <task id="apply_travel" name="Apply Travel" action="Input" type="Begin">
            <executor strategy="Role" value="BDM" />
            <input>
                <column id="TravelAmount" isRequire="true"/>
                <column id="outOfChina" isRequire="true"/>
            </input>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="Success" valueType="Equal"/>
                    </condition>
                    <trigger ref="bdm_leader_approve"/>
                </rule>
            </ruleList>
        </task>
        <task id="bdm_leader_approve" name="BDM Leader Approve" action="Approve" type="Process">
            <executor strategy="Leader" value=""/>
            <submit>
                <column id="action"/>
                <column id="TravelAmount"/>
                <column id="outOfChina"/>
            </submit>
            <ruleList>
                <rule id="in_china_to_end">
                    <condition>
                        <column id="action" value="Approve" valueType="Equal"/>
                        <column id="TravelAmount" value="4000" valueType="Smaller"/>
                        <column id="outOfChina" value="False" valueType="Equal"/>
                    </condition>
                    <trigger ref="end"/>
                </rule>
               <rule id="out_china_to_manager">
                   <condition>
                       <column id="action" value="Approve" valueType="Equal"/>
                       <column id="TravelAmount" value="4000" valueType="Smaller"/>
                       <column id="outOfChina" value="True" valueType="Equal"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="greater_than_4000">
                   <condition>
                       <column id="action" value="Approve" valueType="Equal"/>
                       <column id="TravelAmount" value="4000" valueType="Greater"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="reject">
                <condition>
                    <column id="action" value="Reject" valueType="Equal"/>
                </condition>
                <trigger  ref="apply_travel"/>
            </rule>
            </ruleList>
        </task>
        <task id="manager_approve" name="Manager Approve" action="Approve" type="Process">
            <executor strategy="Constant" value="">
                <user_id id="255" />
                <user_id id="3383" />
            </executor>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="Approve" valueType="Equal"/>
                    </condition>
                    <trigger ref="end"/>
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="Reject" valueType="Equal"/>
                    </condition>
                    <trigger ref="apply_travel"/>
                </rule>
            </ruleList>
        </task>
    </taskList>
</process>

=== leedarKen/cflow/src/test/resource/process/bdm_travel_pre-application_process_1.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>

<process id="bdm_travel_pre-application_process" name="BDM Travel Process" version="1.0.0" startUserRole="BDM"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="process.xsd">
    <processForm>
        <column id="TravelAmount" type="Currency" name="Travel Amount"/>
        <column id="outOfChina" type="String" name="Out Of China"/>
    </processForm>

    <taskList>
        <task id="apply_travel" name="Apply Travel" action="Input" type="Begin">
            <executor strategy="Role" value="BDM" />
            <input>
                <column id="TravelAmount" isRequire="true"/>
                <column id="outOfChina" isRequire="true"/>
            </input>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="Success" valueCondition="Equal"/>
                    </condition>
                    <trigger ref="bdm_leader_approve"/>
                </rule>
            </ruleList>
        </task>
        <task id="bdm_leader_approve" name="BDM Leader Approve" action="Approve" type="Process">
            <executor strategy="Leader" value="301"/>
            <submit>
                <column id="action"/>
                <column id="TravelAmount"/>
                <column id="outOfChina"/>
            </submit>
            <ruleList>
                <rule id="in_china_to_end">
                    <condition>
                        <column id="action" value="Approve" valueCondition="Equal"/>
                        <column id="TravelAmount" value="FromDataBase" valueCondition="Smaller" type="1"/>
                        <column id="outOfChina" value="False" valueCondition="Equal"/>
                    </condition>
                    <trigger ref="end"/>
                </rule>
               <rule id="out_china_to_manager">
                   <condition>
                       <column id="action" value="Approve" valueCondition="Equal"/>
                       <column id="TravelAmount" value="FromDataBase" valueCondition="Smaller"/>
                       <column id="outOfChina" value="True" valueCondition="Equal"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="greater_than_4000">
                   <condition>
                       <column id="action" value="Approve" valueCondition="Equal"/>
                       <column id="TravelAmount" value="FromDataBase" valueCondition="Greater"/>
                   </condition>
                   <trigger ref="manager_approve"/>
               </rule>
               <rule id="reject">
                <condition>
                    <column id="action" value="Reject" valueCondition="Equal"/>
                </condition>
                <trigger  ref="apply_travel"/>
            </rule>
            </ruleList>
        </task>
        <task id="manager_approve" name="Manager Approve" action="Approve" type="Process">
            <executor strategy="Others" value="ByTravelAmount">
            </executor>
            <submit>
                <column id="action"/>
            </submit>
            <ruleList>
                <rule>
                    <condition>
                        <column id="action" value="Approve" valueCondition="Equal"/>
                    </condition>
                    <trigger ref="end"/>
                </rule>
                <rule>
                    <condition>
                        <column id="action" value="Reject" valueCondition="Equal"/>
                    </condition>
                    <trigger ref="apply_travel"/>
                </rule>
            </ruleList>
        </task>
    </taskList>
</process>
