=== leedarKen/cflow/src/main/resources/com.cosft.resource.cflow.xml/process.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="process">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="form" type="formType" minOccurs="0"/>
                <xs:element name="tasks" type="tasksType" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string"/>
            <xs:attribute name="name" type="xs:string"/>
            <xs:attribute name="version" type="xs:float"/>
            <xs:attribute name="startUserRole" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="formType">
        <xs:sequence>
            <xs:element name="column" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="type" type="xs:string"/>
                    <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tasksType">
        <xs:sequence>
            <xs:element name="task" type="taskType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="taskType">
        <xs:sequence>
            <xs:element name="input" type="inputType" maxOccurs="1" minOccurs="0"/>
            <xs:element name="rule" type="ruleType" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="action" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="inputType">
        <xs:sequence>
            <xs:element name="column" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="isRequire" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>

    </xs:complexType>
    <xs:complexType name="ruleType">
        <xs:sequence>
            <xs:element name="condition" type="resultType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="column" type="xs:string"/>
        <xs:attribute name="result" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="resultType">
        <xs:sequence>
            <xs:element name="toTask" minOccurs="1" type="toTaskType" />
            <xs:element name="toRole" minOccurs="1" type="toRoleType" />
        </xs:sequence>
        <xs:attribute name="column" type="xs:string"/>
        <xs:attribute name="result" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="toTaskType">
        <xs:sequence>
            <xs:element name="toTask" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="ref" type="xs:string"/>
        <xs:attribute name="to" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="toRoleType">
        <xs:sequence>
            <xs:element name="toRole" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="toStrategy" type="xs:string"/>
        <xs:attribute name="role" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== leedarKen/cflow/src/main/resources/com.cosft.resource.cflow.xml/bdm_travel_process.xml
<?xml version="1.0" encoding="UTF-8"?>

<process id="bdm_travel" name="BDM Travel Process" version="1.0" startUserRole="BDM"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="process.xsd">
    <form>
        <column id="TravelAmount" type="number" name="Travel Amount"/>
        <column id="DepartureDate" type="date" name="Departure Date"/>
        <column id="ReturnDate" type="date" name="Return Date"/>
        <column id="Destination" type="String" name="Destination"/>
        <column id="Reason" type="String" name="Reason"/>
        <column id="outOfChina" type="String" name="Out Of China"/>
    </form>

    <tasks>
        <task id="apply_travel" name="Apply Travel" action="input" type="begin">
            <input>
                <column id="TravelAmount" isRequire="true"/>
                <column id="DepartureDate" isRequire="true"/>
                <column id="ReturnDate" isRequire="true"/>
                <column id="Destination" isRequire="true"/>
                <column id="Reason" isRequire="true"/>
                <column id="outOfChina" isRequire="true"/>
            </input>
            <rule>
                <condition column="action" condition="success" type="equal">
                    <toTask ref="bdm_leader_approve"/>
                    <toRole toStrategy="creator" role="Fiance"/>
                </condition>
            </rule>
        </task>
        <task id="bdm_leader_approve" name="BDM Leader Approve" action="approve">
            <rule>
                <condition column="action" result="approve" type="equal">
                   <!-- <condition column="TravelAmount" condition="4000" type="grater">
                        <toTask ref="manager_approve"/>
                        <toRole toStrategy="role" role="VP"/>
                    </condition>-->
                    <condition column="TravelAmount" condition="4000" type="smaller">
                        <condition column="outOfChina" condition="Yes" type="equal">
                            <toTask ref="manager_approve"/>
                            <toRole toStrategy="role" role="VP"/>
                        </condition>
                        <condition column="outOfChina" condition="No" type="equal">
                            <toTask ref="fiance_approve"/>
                            <toRole toStrategy="role" role="Fiance"/>
                        </condition>
                    </condition>
                </condition>
                <condition column="action" result="reject" type="equal">
                    <toTask ref="apply_travel"/>
                    <toRole toStrategy="creator" role="Fiance"/>
                </condition>
            </rule>
        </task>
        <task id="manager_approve" name="Manager Approve" action="approve">
            <rule>
                <condition column="action" result="approve" type="equal">
                    <toTask ref="admin_order"/>
                    <toRole toStrategy="role" role="admin"/>
                </condition>
                <condition column="action" result="reject" type="equal">
                    <toTask ref="apply_travel"/>
                    <toRole toStrategy="creator" role="Fiance"/>
                </condition>
            </rule>
        </task>
        <task id="fiance_approve" name="Fiance Approve" action="approve">
            <rule>
                <condition column="action" result="approve" type="equal">
                    <toTask ref="admin_order"/>
                    <toRole toStrategy="role" role="admin"/>
                </condition>
                <condition column="action" result="reject" type="equal">
                    <toTask ref="apply_travel"/>
                    <toRole toStrategy="creator" role="Fiance"/>
                </condition>
            </rule>
        </task>

        <task id="admin_order" name="Admin Order" action="notice" type="end">
            <rule>
                <condition column="action" result="finish" type="equal">
                    <toTask to="end"/>
                </condition>
                <condition column="action" result="cancel" type="equal">
                    <toTask ref="apply_travel"/>
                    <toRole toStrategy="creator" role="Fiance"/>
                </condition>
            </rule>
        </task>
    </tasks>

</process>
